### ISSUE TITLE
Feature Request: Detailed Logging

### ISSUE THREAD

**Issue by hblaschka** [homeean/presence#2]
For users running homeean-presence installed via homeean the Debug-Option is probably not a good solution. An optional logile (with various loglevels) configurable via the config (including logging to syslog) could be helpful for tests.

**Comment by stfnhmplr** [comment]
With the latest version homeean-presence offers different log levels and a file output to `~/.homeean-presence/homeean-presence.log` 

The default log level is `INFO`. You can set it to `DEBUG` (or another one) with the environment variable `LOG_LEVEL`

so i'll close this.
