### ISSUE TITLE
Cannot GET /homeean-presence/

### ISSUE THREAD

**Issue by vascoavanzini** [homeean/presence#3]
Hi
I installed the homeean-presence through the buildscript. I can start homeean-presence with systemd without errors. But when i open the url, i get the following message:

URL: http://192.168.1.10:3000/homeean-presence/aprilbeacon
-----------------------------------
Cannot GET /homeean-presence/AprilBeacon

-----------------------------------
The debug mode throws the following messages:

```
pi@raspberrypi:~/.homeean-presence $ DEBUG=homeean-presence homeean-presence
homeean-presence
2018 by stfnhmplr | homeean.de
  homeean-presence running on node v8.11.3 +0ms
  homeean-presence load config from /home/pi/.homeean-presence/config.json +3ms
  homeean-presence AprilBeacon registered as person +0ms
  homeean-presence setting up webhook http://192.168.1.10:3001/homeean-presence/aprilbeacon +6ms
  homeean-presence start tracking for AprilBeacon +4ms
  homeean-presence AprilBeacon: last_seen: never [null] +30s
  homeean-presence AprilBeacon: last_seen: 2018-08-07T10:55:05.901Z [bleacon] +30s
  homeean-presence AprilBeacon is present. +1m
  homeean-presence somebody @home, triggering webhook for presence +2ms
  homeean-presence received status 200 +865ms
  homeean-presence AprilBeacon: last_seen: 2018-08-07T10:55:34.232Z [bleacon] +30s
  homeean-presence AprilBeacon: last_seen: 2018-08-07T10:56:03.849Z [bleacon] +30s

```
Any ideas why i cannot get the webhooks?

Thanks and best regards
vasco

**Comment by vascoavanzini** [comment]
I changed the port to 3001 to eliminate the

**Comment by stfnhmplr** [comment]
Is this still an issue? You should use the correct URL as it appears in the output.
`http://192.168.1.10:3001/homeean-presence/aprilbeacon`

**Comment by stfnhmplr** [comment]
Since there has been no reaction, I assume that the problem has been solved. So I close this issue. If the problem still exists, you are welcome to reopen the issue.
