### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by SteffenTM** [homeean/presence#8]
Hello, i tryed to install the homeean-presence on my raspberry via homeean-script and also with the npm-installation. I hasn't worked, i got the following messages:

![presence error](https://user-images.githubusercontent.com/51925871/60784949-67f45700-a151-11e9-92aa-b1f922c6495f.JPG)

Has anyone an idea whats wrong?

Thanx, Steffen

**Comment by stfnhmplr** [comment]
What platform did you try to install on?
